app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    # path('', views.webcam, name='webcam'),
    path('report/', views.report_chart, name='report'),
    path('subject_data/', views.subject_data),
    path('subject_data_week/', views.subject_data_week),
    path('conc_daily/', views.conc_daily, name='conc_daily'),
    path('conc_week/', views.conc_week, name='conc_week'),
    path('emotion_daily/', views.emotion_daily, name='emotion_daily'),
    path('emotion_week/', views.emotion_week, name='emotion_week'),
    path('home/', views.home, name='home'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from app import views
from user import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('app/', views.webcam),
    path('app/', include('app.urls')),
    path('', include('user.urls')),
]

templates/app/home_tab.html
{% load static %}
<style>

  .text-center.title{
    font-family: 'Jua', sans-serif;
    font-size: 2rem;
  }

  .text-center.content{
    font-family: 'Sunflower', sans-serif;
    border-radius: 5px;
    padding: 0.6em 1em;
    background: #F1F1F3;
    font-size: 1rem;
  }
  
</style>

<div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
  <div class="row">
    <span class="col m-1 p-3">
      <h4 class="text-center title">
        {{ user_info.parents_id }}님, <br>환영합니다!
      </h4>
    </span>
    <span class="col">
      <img src="{% static 'img/welcome_cats.png' %}" class="d-inline-block align-top img-fluid" alt="welcome">
    </span>
  </div>
  <p class="m-3 text-center content">
    {{ user_info.user_name }} 님의 <br> {{ week.0.0 }}, {{ week.0.1 }} 종합 report 입니다.</p>
  <div id=home_frame>
    <script>
      $.ajax({
        url: "{% url 'app:home' %}",
        type: "POST",
        success: function (data) {
          console.log('home Ajax Success!');
          console.log(data)
          console.log(data.todays_conc)
          console.log(data.todays_emo)

          const home_frame = document.getElementById('home_frame')
          home_frame.innerHTML =`
          <div class="d-flex flex-row bd-highlight mb-3 justify-content-center">
          <div class="p-2 bd-highlight flex-sm-fill">
            <div class="text-center">
              <span>📝등급</span>
            </div>
            <div class="text-center">
              <img class='image-thumbnail d-inline-block align-top img-fluid' style="width:150px; height:auto;" src="`+data.todays_conc+`" alt="grade.png">
            </div>
          </div>
          <div class="p-2 bd-highlight flex-sm-fill">
            <div class="text-center">
              <span>📝감정</span>
            </div>
            <div class="text-center">
              <img class='image-thumbnail d-inline-block align-top img-fluid' style="width:150px; height:auto;" src="`+data.todays_emo.todays_emo_url+`" alt="grade.png">
              <p class="text-center"> `+data.todays_emo.todays_emo+`</p>
            </div>
          </div>
        </div>
          `
        },
        error: function () {
          console.log("home Ajax fail!");
        }
      }) 
    </script>
  </div>
  <div class="text-center">
    <p>🌷 Best Shot 🌷</p>
    <img src="{% static 'img/userbestshot.jpg' %}" class="d-inline-block align-top img-fluid"
     style="width:300px; height:180px; border-radius:10px; box-shadow:5px 5px 5px #d7d7db" alt="bestshot">
  </div>

</div>