app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    # path('', views.webcam, name='webcam'),
    path('report/', views.report_chart, name='report'),
    path('subject_data/', views.subject_data),
    path('subject_data_week/', views.subject_data_week),
    path('conc_daily/', views.conc_daily, name='conc_daily'),
    path('conc_week/', views.conc_week, name='conc_week'),
    path('emotion_daily/', views.emotion_daily, name='emotion_daily'),
    path('emotion_week/', views.emotion_week, name='emotion_week'),
    path('home/', views.home, name='home'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from app import views
from user import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('app/', views.webcam),
    path('app/', include('app.urls')),
    path('', include('user.urls')),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    # path('login/', views.login),
    path('profile/', views.profile, name="profile"),
    path('mypage/', views.mypage, name='mypage'),
    path('timetable/', views.timetable),
    path('timetablevalue/', views.timetablevalue),
    path('logout/', views.logout, name="logout"),

    path('', views.login, name="login"),
    path('check_user', views.check_user, name="check_user")

    # path('signup/', views.signup, name='signup'),
    # path('login/', views.login, name='login'),
    # path('main/', views.main, name='main'),
    # path('profile/', views.profile, name='profile')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- CSS -->
    <!-- Bootstrap CSS version 4.5 -->
    <link rel='stylesheet' href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css">

    <!-- JQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>

    <!-- JQuery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Chart.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js"></script>
    <script src="{% static 'js/chartjs-plugin-doughnutlabel.min.js' %}"></script>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap"
        rel="stylesheet">
    
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Black+And+White+Picture&family=Black+Han+Sans&family=Cute+Font&family=Do+Hyeon&family=Dokdo&family=East+Sea+Dokdo&family=Gaegu&family=Gamja+Flower&family=Gothic+A1&family=Gugi&family=Hi+Melody&family=Jua&family=Kirang+Haerang&family=Nanum+Brush+Script&family=Nanum+Gothic&family=Nanum+Gothic+Coding&family=Nanum+Myeongjo&family=Nanum+Pen+Script&family=Noto+Sans+KR&family=Noto+Serif+KR&family=Poor+Story&family=Single+Day&family=Song+Myung&family=Stylish&family=Sunflower:wght@300&family=Yeon+Sung&display=swap" rel="stylesheet">

    

    <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">


    <title>AI_Conc</title>
</head>


<body>
    <!-- Header -->
    <nav class="navbar navbar-light bg-white top">
        <a class="navbar-brand" href="{% url 'app:report'%}">
          <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">
          AI_Conc&Emo
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </nav>
    <div class="collapse sidemenu" id="navbarToggle">
        <ul class="list-group">
            <form action="{% url 'app:report' %}" method="POST" id="menu-list">
                {% csrf_token %}
                <script>
                    $.ajax({
                        url: "{% url 'user:check_user' %}",
                        method: "GET",
                        success: function(data){
                            const menu = document.getElementById('menu-list');
                            
                            for(i of Object.keys(data)){
                                menu.innerHTML += `
                                    <div class="container-fulid">
                                        <input type="submit" name='user_id' value="${i}"> ${data[i]}
                                    </div>
                                `
                            }
                        }
                    })
                </script>   
            </form>         
            <li class="list-group-item"><a href="{% url 'user:profile' %}">마이페이지</a></li>
            <li class="list-group-item"><a href="{% url 'user:logout' %}">로그아웃</a></li>
        </ul>
    </div>
    <!-- Navigation -->
    <!-- <nav>
        <div class="nav nav-tabs nav-justified" id="nav-tab" role="tablist">
            <button class="nav-link active" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-home" type="button" role="tab" aria-controls="nav-home" aria-selected="true">Home</button>
            <button class="nav-link" id="nav-subject-tab" data-bs-toggle="tab" data-bs-target="#nav-subject" type="button" role="tab" aria-controls="nav-subject" aria-selected="false">과목</button>
            <button class="nav-link" id="nav-conc-tab" data-bs-toggle="tab" data-bs-target="#nav-conc" type="button" role="tab" aria-controls="nav-conc" aria-selected="false">집중도</button>
            <button class="nav-link" id="nav-emotion-tab" data-bs-toggle="tab" data-bs-target="#nav-emotion" type="button" role="tab" aria-controls="nav-emotion" aria-selected="false">감정</button>
        </div>
    </nav> -->

    {% block content %}

    {% endblock %}
</body>

</html>

templates/chart.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% include 'nav.html' %}

<!-- tab for page moving -->
<div class="tab-content" id="nav-tabContent">
  <!-- 1. Home Tab -->
  {% include 'app/home_tab.html' %}

  <!-- 2. Subject Tab -->
  {% include 'app/subject_tab.html' %}

  <!-- 3. Concentration Tab -->
  {% include 'app/conc_tab.html' %}

  <!-- 4. Emotion Tab -->
  {% include 'app/emotion_tab.html' %}
</div>


<!-- bootstrap breakpoint
<div class='container-sm'> 100% wide until small breakpoint </div>
<div class='container-md'> 100% wide until medium breakpoint </div>
<div class='container-lg'> 100% wide until large breakpoint </div>
<div class='container-xl'> 100% wide until extra breakpoint </div>
<div class='container-xxl'> 100% wide until extra extra large breakpoint </div> -->



<!-- EventListner -->
<!-- 과목 1일 -->
<!-- <script type="text/javascript" src="{% static 'js/app/subject_daily.js' %}"></script> -->

<!-- 과목 1주 -->
<!-- <script type="text/javascript" src="{% static 'js/app/subject_week.js' %}"></script> -->

<!-- 3-1. conc_daily -->
<script type="text/javascript" src="{% static 'js/app/conc_daily.js' %}"></script>

<!-- 3-2. conc_week -->
<script type="text/javascript" src="{% static 'js/app/conc_week.js' %}"></script>

<!-- 4-1. emotion_daily -->
<script type="text/javascript" src="{% static 'js/app/emotion_daily.js' %}"></script>

<!-- 4-2. emotion_week -->
<script type="text/javascript" src="{% static 'js/app/emotion_week.js' %}"></script>

{% endblock %}

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        <!-- 필드 오류 출력 -->
            <!-- 입력값 누락, 형식에 맞지 않음 -->
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
        <!-- 넌필드 오류 출력 -->
            <!-- 입력값과 관계없이 발생한 오류 -->
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
{% endif %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
    <table border='1'>
        <tr>
            <td>ParentsID</td>
            <td><input type="text" placeholder = "Enter Name.." name="parents_id" required /></td>
            
        </tr>
        <tr>
            <td>Password</td>
            <td><input type="password"
                 name="parents_pw" required/></td>
        </tr>
        {% comment %} <tr>
            <td>re-Password</td>
            <td><input type="password" name="repwd" pattern="" required /></td>
        </tr> {% endcomment %}
    </table>
    <hr/>
    <input type="submit" value="submit"/>
    {% if messages %}
    {% for result in messages %}
    {{result}}
    {% endfor %}
    {% endif %}
    </form>
</body>
</html>

templates/nav.html
<!-- Navigation -->
<nav>
    <div class="nav nav-tabs nav-justified nav-tab-menu" id="nav-tab" role="tablist">
        <a class="nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab"
            aria-controls="nav-home" aria-selected="true">Home</a>
        <a class="nav-link" id="nav-subject-tab" data-toggle="tab" href="#nav-subject" role="tab"
            aria-controls="nav-subject" aria-selected="false">과목</a>
        <a class="nav-link" id="nav-conc-tab" data-toggle="tab" href="#nav-conc" role="tab" aria-controls="nav-conc"
            aria-selected="false">집중도</a>
        <a class="nav-link" id="nav-emotion-tab" data-toggle="tab" href="#nav-emotion" role="tab"
            aria-controls="nav-emotion" aria-selected="false">감정</a>
    </div>
</nav>