app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    # path('', views.webcam, name='webcam'),
    path('report/', views.report_chart, name='report'),
    path('subject_data/', views.subject_data),
    path('subject_data_week/', views.subject_data_week),
    path('conc_daily/', views.conc_daily, name='conc_daily'),
    path('conc_week/', views.conc_week, name='conc_week'),
    path('emotion_daily/', views.emotion_daily, name='emotion_daily'),
    path('emotion_week/', views.emotion_week, name='emotion_week'),
    path('home/', views.home, name='home'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from app import views
from user import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('app/', views.webcam),
    path('app/', include('app.urls')),
    path('', include('user.urls')),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    # path('login/', views.login),
    path('profile/', views.profile, name="profile"),
    path('mypage/', views.mypage, name='mypage'),
    path('timetable/', views.timetable),
    path('timetablevalue/', views.timetablevalue),
    path('logout/', views.logout, name="logout"),

    path('', views.login, name="login"),
    path('check_user', views.check_user, name="check_user")

    # path('signup/', views.signup, name='signup'),
    # path('login/', views.login, name='login'),
    # path('main/', views.main, name='main'),
    # path('profile/', views.profile, name='profile')
]

user/models.py
from django.db import models

# Create your models here.

user/views.py
from django.http.response import JsonResponse
from django.shortcuts import render, redirect
from django.http import HttpResponse
# from mysql import DB
from django.contrib import messages
from app.models import Parents, User, Timetable
from django.views.decorators.csrf import csrf_exempt

from django.core.exceptions import ObjectDoesNotExist
import datetime

# Create your views here.
def login(request):

    if request.method == "POST":
        print(request.POST)
        parents_id = request.POST['uid']
        parents_pw = request.POST['upw']
        try:
            member = Parents.objects.get(parents_id=parents_id)
            if (member.parents_id == parents_id) & (member.parents_pw == parents_pw):
                request.session['uid'] = member.parents_id

                return render(request, 'user/check_user.html')
            else :
                return redirect('/')
        
        except Parents.DoesNotExist:
            messages.error(request, "로그인 실패")
            return redirect('/')
    
    # request.method == "GET"
    else:
        return render(request, 'user/login.html')


def check_user(request):
    
    if request.method == "POST":
        print("check_user POST: ", request.POST)
        request.session['cid'] = request.POST.get('user_id')
        return redirect('/app/report')
    else:
        children = User.objects.filter(parents_id=request.session['uid'])
        content = {}
        for data in children:
            content[data.user_id] = data.user_name

        return JsonResponse(content)

def logout(request):
    if request.session.get('uid'):
        del(request.session['uid'])
    return redirect('/')



def signup(request):
    if request.method=="POST":
        # print(request.POST.get('signup_class').__class__)
        try:
            parents = Parents.objects.get(parents_id=request.POST.get('signup_uid'))

            return render(request, 'user/signup.html')
            # return redirect('signup')

        except Parents.DoesNotExist:
            new_user = Parents(parents_id=request.POST.get('signup_uid'), parents_pw=request.POST.get('signup_upw'))

            index = User.objects.last()
            index = index.user_id + 1
            new_children = User(user_id=index, user_name=request.POST.get('signup_name'), user_age=int(request.POST.get('signup_age')),
                            user_sex=int(request.POST.get('gender')), user_class=int(request.POST.get('signup_class')), parents_id=request.POST.get('signup_uid'))
            new_user.save()
            new_children.save()

            startarray = [datetime.time(9, 0, 0), datetime.time(10, 0, 0), datetime.time(11, 0, 0),
                        datetime.time(12, 0, 0), datetime.time(
                            13, 0, 0), datetime.time(14, 0, 0),
                        datetime.time(15, 0, 0)]
            endarray = [datetime.time(9, 50, 0), datetime.time(10, 50, 0), datetime.time(11, 50, 0),
            datetime.time(12, 50, 0), datetime.time(
                13, 50, 0), datetime.time(14, 50, 0),
            datetime.time(15, 50, 0)]

            for j in range(7):
                for i in range(1, 6):
                    savetimetable = Timetable()
                    savetimetable.subject_day = i
                    savetimetable.user_id = index
                    savetimetable.subject = ''
                    savetimetable.subject_start_time = startarray[j]
                    savetimetable.subject_finish_time = endarray[j]

                    savetimetable.save()

            return redirect('/')
            
    else:
        return render(request, 'user/signup.html')


@csrf_exempt
def timetable(request):
    parent_id=request.session['uid']
    children = User.objects.filter(parents_id=parent_id).first()
    request.session['user_id'] = children.user_id
    request.session['user_name'] = children.user_name

    user_timetable = Timetable.objects.filter(user_id=children.user_id).order_by('subject_day','subject_start_time')
    mon = []
    tue = []
    wed = []
    thu = []
    fri = []

    for idx, i in enumerate(user_timetable):
        if idx <7 :
            mon.append(i.subject)
        elif idx < 14 :
            tue.append(i.subject)
        elif idx < 21 :
            wed.append(i.subject)
        elif idx < 28 :
            thu.append(i.subject)
        else :
            fri.append(i.subject)


    
    content = {'mon' : mon, 'tue' : tue, 'wed':wed, 'thu':thu, 'fri':fri}

    return render(request, "user/timetable.html", content)


@csrf_exempt
def timetablevalue(request):
    print("ajax success")
    if request.method == "POST":
        data = request.POST.get('id')
        data = data[1:-1].replace('"', '').split(',')
        parent_id=request.session['uid']
        children = User.objects.filter(parents_id=parent_id).first()
        # print(data)
        # print(f"data : {data}" )
        # print(f"data type : {type(data)}")
        user_timetable = Timetable.objects.filter(user_id=children.user_id).order_by('subject_day','subject_start_time')
        for idx,i in enumerate(user_timetable):
            i.subject = data[idx]
            i.save()  

    return HttpResponse('')
    

@csrf_exempt
def profile(request):
    parents_id=request.session.get('parents_id')

    if request.method=="POST":
        if request.POST.get('user_id') and request.POST.get('user_name') and request.POST.get('user_age') and request.POST.get('user_sex') and request.POST.get('user_class') and request.POST.get('grade'):
            saverecord=User()
            saverecord.user_id=request.POST.get('user_id')
            saverecord.user_name=request.POST.get('user_name')
            saverecord.user_age=request.POST.get('user_age')
            saverecord.user_sex=request.POST.get('user_sex')
            saverecord.user_class=request.POST.get('user_class')
            saverecord.grade=request.POST.get('grade')
            saverecord.parents_id=request.session.get('parents_id')

            saverecord.save()

            messages.success(request, "프로필 수정 완료")
            request.session['user_name']=request.POST.get('user_name')
            return render(request, 'user/profile.html', {})

            # return redirect("/app/report")
    else:
        return render(request, 'user/profile.html', {'parents':parents_id})
        # return redirect("/app/report")

def mypage(request):

    if request.method == "POST":
        pass
    else:
        content = {}
        
        children = User.objects.filter(parents_id=request.session['uid'])

        for data in children:
            content[data.user_id] = [data.user_name, data.user_age]

        return JsonResponse(content)

templates/user/check_user.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Bootstrap CSS version 4.5 -->
  <link rel='stylesheet' href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css">
  <!-- JQuery -->
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>

  <title>Document</title>
</head>

<body>
  <!-- <style>
    div {
      border: 1px solid red;
    }
  </style> -->

  <!-- Header -->
  <nav class="navbar navbar-light bg-light">
    <a class="navbar-brand" >
      <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">
      AI_Conc&Emo
    </a>
  </nav>

  <div class="mt-5 container-sm">
    <div class="card">
      <div class="row align-items-center">
        <div class="col-sm">
          <img class="img-fluid" src="{% static 'img/check_box.png' %}" style="max-width: 100%; height:50%; object-fit:cover">
        </div>

        <div class="col-sm">
          <div class="card-title" style="margin-top:30px;">
            <h2 class="card-title text-center" style="color:#113366;">자녀 선택</h2>
          </div>

          <div class="card-body ">
            <form class="form-signin" method="POST" action="{% url 'user:check_user' %}">
              {% csrf_token %}
              {% include 'form_errors.html' %}

              <div class='form-group'>
                <div class="btn-group-toggle" data-toggle="buttons" id="select_children">
                    자녀 선택

                    <script>
                        $.ajax({
                            url:'../check_user',
                            method: 'GET',
                            success: function(data){

                                const select_children = document.getElementById('select_children');

                                for(i of Object.keys(data)){
                                    select_children.innerHTML += `
                                        <label class="btn btn-secondary">
                                            <input class="form-control" type="radio" name="user_id" value="${i}"> ${data[i]}
                                        </label>
                                    `
                                }
                                
                            }
                        })
                    </script>
                    
                </div>
              </div>

              <div class="checkbox">
                <label>
                  <input type="checkbox" value="remember-me"> 기억하기
                </label>
              </div>

              <button id="btn-Yes" class="btn btn-lg btn-primary btn-block" type="submit">선 택 완 료</button>
            </form>

          </div>
        </div>
      </div>

    </div>
  </div>

</body>

</html>

templates/user/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Bootstrap CSS version 4.5 -->
  <link rel='stylesheet' href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css">
  <!-- JQuery -->
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>

  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Black+And+White+Picture&family=Black+Han+Sans&family=Cute+Font&family=Do+Hyeon&family=Dokdo&family=East+Sea+Dokdo&family=Gaegu&family=Gamja+Flower&family=Gothic+A1&family=Gugi&family=Hi+Melody&family=Jua&family=Kirang+Haerang&family=Nanum+Brush+Script&family=Nanum+Gothic&family=Nanum+Gothic+Coding&family=Nanum+Myeongjo&family=Nanum+Pen+Script&family=Noto+Sans+KR&family=Noto+Serif+KR&family=Poor+Story&family=Single+Day&family=Song+Myung&family=Stylish&family=Sunflower:wght@300&family=Yeon+Sung&display=swap" rel="stylesheet">

  <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">

  <title>AI_Conc</title>
</head>

<body>
  <!-- Header -->
  <nav class="navbar navbar-light bg-light login-menu">
    <a class="navbar-brand" >
      <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">
      AI_Conc&Emo
    </a>
  </nav>

  <div class="mt-5 container-sm login-menu">
    <div class="card">
      <div class="row align-items-center">
        <div class="col-sm">
          <img class="img-fluid" src="{% static 'img/true_friends.png' %}" style="max-width: 100%; height:50%; object-fit:cover">
        </div>

        <div class="col-sm">
          <div class="card-title" style="margin-top:30px;">
            <h2 class="card-title text-center" style="color:#113366;">로그인</h2>
          </div>

          <div class="card-body ">
            <form class="form-signin" method="POST" action="{% url 'user:login' %}">
              {% csrf_token %}
              {% include 'form_errors.html' %}

              <div class='form-group'>
                <h5 class="form-signin-heading">아이디</h5>
                <label for="inputEmail" class="sr-only">Your ID</label>
                <input type="text" class="form-control" id="uid" name="uid"
                  value="{{ form.username.value | default_if_none:'' }}" placeholder="Your ID" required autofocus><BR>
              </div>

              <div class='form-group'>
                <h5 class="form-signin-heading">비밀번호</h5>
                <label for="inputPassword" class="sr-only">Password</label>
                <input type="password" class="form-control" id="upw" name="upw"
                  value="{{ form.password.value | default_if_none:'' }}" placeholder="Password" required><br>
              </div>

              <div class="checkbox">
                <label>
                  <input type="checkbox" value="remember-me"> 기억하기
                </label>
              </div>

              <button id="btn-Yes" class="btn btn-lg btn-primary btn-block" type="submit">로 그 인</button>
            </form>

            <div class="mt-1">
              <button id="btn-No1" class="btn btn-lg btn-primary btn-block" type="submit">아이디/비밀번호 찾기</button>
            </div>

            <div class="mt-1">
              <button id="btn-No2" class="btn btn-lg btn-primary btn-block" type="button" onclick="location.href='/signup'">회원가입</button>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>

</body>

</html>

templates/user/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="card m-3 p-3" style="width: 18rem;">
    <img src="{% static 'img/quick_chat.png' %}" class="card-img-bottom" alt="사용자 프로필 이미지">
    <div class="card-body mt-3 pt-3" id="profile">
        <h4 class="card-title"> 사용자 정보</h4>
        <p class="card-text">{{ parents.parents_id }} 프로필</p>
        <a href="{% url 'user:profile' %}" class="btn btn-primary">Go</a>
        {% comment %} <a href="{% url 'user:timetable' %}" class="btn btn-primary">Go</a> {% endcomment %}
        <script>
            $.ajax({
                url: "../mypage",
                method: "GET",
                success: function (data) {
                    console.log(data);
                    const profile = document.getElementById('profile');

                    for (i of Object.keys(data)) {
                        profile.innerHTML += `
                                <p class="card-text pt-3">${data[i][0]} 프로필</p>
                                <a href="{% url 'user:profile' %}" class="btn btn-primary">Go</a>
                            `
                    }


                    // 자녀 추가 버튼
                    //profile.innerHTML += `
                    //    
                    //`
                }
            })
        </script>
    </div>

    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
        자 녀 추 가
    </button>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">자녀정보 기입</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{% url 'user:profile' %}" method="POST">

                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>


</div>

{% endblock %}

templates/user/signup.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS version 4.5 -->
    <link rel='stylesheet' href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css">
    <!-- JQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link
        href="https://fonts.googleapis.com/css2?family=Black+And+White+Picture&family=Black+Han+Sans&family=Cute+Font&family=Do+Hyeon&family=Dokdo&family=East+Sea+Dokdo&family=Gaegu&family=Gamja+Flower&family=Gothic+A1&family=Gugi&family=Hi+Melody&family=Jua&family=Kirang+Haerang&family=Nanum+Brush+Script&family=Nanum+Gothic&family=Nanum+Gothic+Coding&family=Nanum+Myeongjo&family=Nanum+Pen+Script&family=Noto+Sans+KR&family=Noto+Serif+KR&family=Poor+Story&family=Single+Day&family=Song+Myung&family=Stylish&family=Sunflower:wght@300&family=Yeon+Sung&display=swap"
        rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">

    <title>AI_Conc&Emo</title>
</head>

<body>
    <!-- <style>
    div {
      border: 1px solid red;
    }
  </style> -->

    <!-- Header -->
    <nav class="navbar navbar-light bg-light login-menu">
        <a class="navbar-brand">
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt=""
                loading="lazy">
            AI_Conc&Emo
        </a>
    </nav>

    <script>
        function valid(x) {
            var count = 0;
            for (i = 0; i < x.gender[i].length; i++) {
                if (x.gender[i].checked)
                    count += 1;
            }

            if (count == 0) {
                alert("성별을 선택해 주세요!");
            }
        }
    </script>

    <div class="mt-5 container-sm login-menu">
        <div class="card">
            <div class="row align-items-center">
                <div class="col-sm">
                    <img class="img-fluid" src="{% static 'img/quick_chat.png' %}">
                </div>

                <div class="col-sm">
                    <div class="card-title" style="margin-top:30px;">
                        <h2 class="card-title text-center" style="color:#113366;">회원가입</h2>
                    </div>

                    <div class="card-body ">
                        <form class="form-signin" method="POST" action="{% url 'user:signup' %}">
                            {% csrf_token %}
                            {% include 'form_errors.html' %}

                            <div class='form-group'>
                                <h5 class="form-signin-heading">사용자 정보</h5>
                                <label for="inputEmail" class="sr-only">Your ID</label>
                                <input type="text" class="form-control" id="signup_id" name="signup_uid"
                                    value="{{ form.username.value | default_if_none:'' }}" placeholder="Your ID"
                                    required autofocus><BR>
                                <label for="inputPassword" class="sr-only">Password</label>
                                <input type="password" class="form-control" id="signup_upw" name="signup_upw"
                                    value="{{ form.password.value | default_if_none:'' }}" placeholder="Password"
                                    required><br>
                            </div>

                            <div class='form-group' name="c_From">
                                <h5 class="form-signin-heading">자녀 정보</h5>
                                <label for="signup_name" class="sr-only">자녀 이름</label>
                                <input type="text" class="form-control" id="signup_name" name="signup_name"
                                    value="{{ form.text.value | default_if_none:'' }}" placeholder="자녀 이름" required><br>
                                <label for="signup_age" class="sr-only">자녀 나이</label>
                                <input type="text" class="form-control" id="signup_age" name="signup_age"
                                    value="{{ form.text.value | default_if_none:'' }}" placeholder="자녀 나이" required><br>
                                <div class="m-1 p-1">
                                    <div class="btn-group-toggle" data-toggle="buttons">
                                        자녀 성별
                                        <label class="btn btn-secondary">
                                            <input class="form-control" type="radio" name="gender" id="gender_male"
                                                value="0"> 남자
                                        </label>
                                        <label class="btn btn-secondary">
                                            <input class="form-control" type="radio" name="gender" id="gender_femail"
                                                value="1"> 여자
                                        </label>
                                    </div>
                                </div>
                                <label for="signup_class" class="sr-only">자녀 반 번호</label>
                                <input type="text" class="form-control" id="signup_class" name="signup_class"
                                    value="{{ form.text.value | default_if_none:'' }}" placeholder="반 번호" required><br>
                            </div>
                            <button id="btn-Yes" class="btn btn-lg btn-primary btn-block" type="submit"
                                onclick="valid(this.form)">회원가입</button>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>
</body>